# Generated by Django 2.2.3 on 2023-04-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('cor', models.CharField(max_length=50, verbose_name='cor')),
                ('placa', models.CharField(max_length=8, verbose_name='placa')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('a', 'Moto'), ('b', 'Carro'), ('c', 'Pesado')], max_length=100, verbose_name='categoria')),
                ('valor_estacionamento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vehicle')),
            ],
        ),
    ]
